### ISSUE TITLE
Make profile screens fit to Figma.

### ISSUE THREAD

**Issue by francelu** [PeriodPals/periodpals#158]
# Align Profile Screens to Figma Design

## Description
This subtask, part of #82, focuses on aligning the profile screens (`CreateProfileScreen`, `ProfileScreen`, and `EditProfileScreen`) with the Figma design specifications. These updates are essential for task #157 and aim to ensure a consistent and responsive user interface. With these updates, we aim to reduce potential issues when making the screens responsive.
**Note**: the Figma hasn't been updated. With the team, we've decided to remove the email field from the profile screens.

## TODO:
**Warning: Figma isn't up-to-date with removing the email field on the profile screens,**  
- [x] Verify and, if necessary, modify `CreateProfileScreen` to align with our app flow idea.
- [x] Verify and, if necessary, modify `ProfileScreen` to align with the Figma design.
- [x] Verify and, if necessary, modify `EditProfileScreen` to align with the Figma design.
- [ ] Ensure >80% code coverage.
- [x] Adapt or modify UI tests as necessary to reflect design changes.

## Done:
- Initial alignment of `CreateProfileScreen` with Figma.
- Initial alignment of `ProfileScreen` with Figma.
- Initial alignment of `EditProfileScreen` with Figma.
- Verified existing tests and adjusted where required.

Before
`CreateProfileScreen` 
![image](https://github.com/user-attachments/assets/d675d130-e15d-4563-84aa-b75a30168705)
`ProfileScreen`
![image](https://github.com/user-attachments/assets/28e4ecfa-4f86-4c38-87b5-79fd3a47c1e3)
`EditProfileScreen`
![image](https://github.com/user-attachments/assets/4dac7030-9be7-4212-b375-97596133b825)

After
`CreateProfileScreen`
![image](https://github.com/user-attachments/assets/88e2c428-d6a8-4109-bff1-aa2ab6acd576)
`ProfileScreen`
![image](https://github.com/user-attachments/assets/f38a1a5e-f99c-4a50-a321-56fc2c2c2cb6)
`EditProfileScreen`
![image](https://github.com/user-attachments/assets/3bb423f6-f1d8-4be6-886a-698accba3fa2)
